version: "3"
services:
  mysql:
    image: library/mysql:8.0
    container_name: wooma_container
    restart: always
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: wooma_root_secret
      MYSQL_USER: wooma
      MYSQL_PASSWORD: wooma_secret
      MYSQL_DATABASE: wooma_local
      DATABASE_HOST: 127.0.0.1
    ports:
      - '3306:3306'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql/:/var/lib/mysql
    platform: linux/amd64
#  local db용
#  GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
#  FLUSH PRIVILEGES;
